version: "2"

run:
  build-tags:
    - webkit2_41

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - misspell
    - revive

formatters:
  enable:
    - gofumpt

  settings:
    gofumpt:
      extra-rules: true
