server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Кешируем ассеты (Vite обычно хэширует файлы)
  location /assets/ {
    expires 30d;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }
}
